# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G

# tell architectury loom that this project is a forge project.
# this will enable us to use the "forge" dependency.
# using archloom without this is possible and will give you a
# "standard" loom installation with some extra features.
loom.platform=neoforge

minecraft_version=1.21.1
neoForge_version=21.1.133
jei_version=19.42.0.385

license=MIT

mod_version=2.0.0
maven_group=zzzank.mods.kube_jei
archives_base_name=kube_jei
mod_id=kube_jei
mod_name=KubeJEI
mod_author=ZZZank
mod_description=Advanced JEI support for KubeJS 1.21
