# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G

# tell architectury loom that this project is a forge project.
# this will enable us to use the "forge" dependency.
# using archloom without this is possible and will give you a
# "standard" loom installation with some extra features.
loom.platform=neoforge

minecraft_version=26.1.2
neoForge_version=26.1.2.84
jei_version=29.29.0.77
kubejs_version=8.0.4

license=MIT

mod_version=2.0.0
maven_group=zank.mods
archives_base_name=kube_jei
mod_id=kube_jei
mod_name=KubeJEI
mod_author=ZZZank
mod_description=Advanced JEI support for KubeJS

# Publishing
publish.modrinth=[Modrinth repo, for example: bjcrgPcA]
publish.curseforge=1109581
publish.github=[GitHub repo, for example: ZZZank/stonecutter-template-architectury]